name: Release CI
on:
  workflow_call:
    secrets:
      ghcr_password:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          echo "RELEASE_TAG=$(echo "${GITHUB_REF#refs/*/}" | sed 's/^v//' | xargs)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_password }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_TAG }}
